---
services:
  distcc-tcp-server:
    build:
      target: distcc-tcp
    healthcheck:
      start_interval: 1s
      start_period: 30s
    command: ["--enable-tcp-insecure", "--verbose"]
  distcc-tcp-client:
    depends_on:
      distcc-tcp-server:
        condition: service_healthy
    build:
      target: distcc-tcp-test
    environment:
      - DISTCC_HOSTS=distcc-tcp-server

  distcc-tcp-ccache-server:
    build:
      args:
        BASE: distcc-ccache
      target: distcc-tcp
    healthcheck:
      start_interval: 1s
      start_period: 30s
    command: ["--enable-tcp-insecure", "--verbose"]
    volumes:
      - distcc-tcp-ccache:/var/cache/ccache
  distcc-tcp-ccache-client:
    depends_on:
      distcc-tcp-ccache-server:
        condition: service_healthy
    build:
      args:
        BASE: distcc-ccache
      target: distcc-tcp-test
    environment:
      - DISTCC_HOSTS=distcc-tcp-ccache-server
    volumes:
      - distcc-tcp-ccache:/var/cache/ccache

volumes:
  distcc-tcp-ccache:
