---
version: "3"

services:
  distcc-tcp-server:
    image: ${IMAGE}
    healthcheck:
      interval: 3s
    command: ["--enable-tcp-insecure", "--verbose"]
  distcc-tcp-client:
    depends_on:
      distcc-tcp-server:
        condition: service_healthy
    image: ${TEST_IMAGE}
    environment:
      - DISTCC_HOSTS=distcc-tcp-server

  distcc-ssh-server:
    image: ${IMAGE}
    healthcheck:
      interval: 3s
    environment:
      - AUTHORIZED_KEYS
      - SSHD_LOG_LEVEL=VERBOSE
  distcc-ssh-client:
    depends_on:
      distcc-ssh-server:
        condition: service_healthy
    image: ${TEST_IMAGE}
    environment:
      - DISTCC_HOSTS=@distcc-ssh-server
