---
name: build

on:
  schedule:
    - cron: '0 2 * * 1'
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        description: Push built images

env:
  DOCKERHUB_REPOSITORY: ksmanis/gentoo-distcc

jobs:
  build_images:
    strategy:
      fail-fast: false
      matrix:
        arch: ["386", "amd64", "arm/v6", "arm/v7", "arm64", "ppc64le"]
        target: ["tcp", "ssh"]
    name: ${{ matrix.arch }}:${{ matrix.target }} image
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.push) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare build variables
        id: prep
        run: |
          BUILD_DATE=$(date -u +'%Y%m%d')
          BUILD_DATETIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          ARCH=$(echo "${{ matrix.arch }}" | tr -d '/')
          TAG="${ARCH}-${{ matrix.target }}"
          IMAGE="${DOCKERHUB_REPOSITORY}:${TAG}"
          QEMU_PLATFORM=$(echo "${{ matrix.arch }}" | cut -d '/' -f 1)
          {
            echo "BUILD_DATE=${BUILD_DATE}"
            echo "BUILD_DATETIME=${BUILD_DATETIME}"
            echo "IMAGE=${IMAGE}"
            echo "QEMU_PLATFORM=${QEMU_PLATFORM}"
          } >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: matrix.arch != '386' && matrix.arch != 'amd64'
        with:
          platforms: ${{ steps.prep.outputs.QEMU_PLATFORM }}
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          labels: |
            org.opencontainers.image.title=gentoo-distcc
            org.opencontainers.image.description=Gentoo Docker image with distcc that can be used to speed up compilation jobs
            org.opencontainers.image.authors=Konstantinos Smanis <konstantinos.smanis@gmail.com>
            org.opencontainers.image.documentation=https://github.com/KSmanis/docker-gentoo-distcc
            org.opencontainers.image.source=https://github.com/KSmanis/docker-gentoo-distcc
            org.opencontainers.image.url=https://github.com/KSmanis/docker-gentoo-distcc
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.prep.outputs.BUILD_DATETIME }}
          tags: |
            ${{ steps.prep.outputs.IMAGE }}
            ${{ steps.prep.outputs.IMAGE }}-${{ steps.prep.outputs.BUILD_DATE }}
            ghcr.io/${{ steps.prep.outputs.IMAGE }}
            ghcr.io/${{ steps.prep.outputs.IMAGE }}-${{ steps.prep.outputs.BUILD_DATE }}
          platforms: linux/${{ matrix.arch }}
          target: distcc-${{ matrix.target }}
          load: true
      - name: Inspect image
        run: |
          docker image inspect ${{ steps.prep.outputs.IMAGE }}
      - name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.prep.outputs.IMAGE }}-test
          platforms: linux/${{ matrix.arch }}
          target: distcc-${{ matrix.target }}-test
          load: true
      - name: Test distcc
        env:
          IMAGE: ${{ steps.prep.outputs.IMAGE }}
        run: |
          if [ "${{ matrix.target }}" = "ssh" ]; then
            AUTHORIZED_KEYS="$(docker run --rm ${{ steps.prep.outputs.IMAGE }}-test cat .ssh/id_ed25519.pub)"
            export AUTHORIZED_KEYS
          fi
          docker-compose -f docker-compose.test.yml up \
            --abort-on-container-exit \
            --exit-code-from distcc-${{ matrix.target }}-client \
            distcc-${{ matrix.target }}-client distcc-${{ matrix.target }}-server
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.push)
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v2
        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.push)
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.push)
        run: |
          docker push "${{ steps.prep.outputs.IMAGE }}"
          docker push "${{ steps.prep.outputs.IMAGE }}-${{ steps.prep.outputs.BUILD_DATE }}"
          docker push "ghcr.io/${{ steps.prep.outputs.IMAGE }}"
          docker push "ghcr.io/${{ steps.prep.outputs.IMAGE }}-${{ steps.prep.outputs.BUILD_DATE }}"
  build_manifests:
    strategy:
      matrix:
        target: ["tcp", "ssh"]
    name: ${{ matrix.target }} manifest
    runs-on: ubuntu-latest
    needs: build_images
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.push)
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push manifest list
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          ARCHES=("386" "amd64" "armv6" "armv7" "arm64" "ppc64le")
          BUILD_DATE=$(date -u +'%Y%m%d')
          MANIFEST_TAGS=("${{ matrix.target }}" "${{ matrix.target }}-${BUILD_DATE}")

          for MANIFEST_TAG in "${MANIFEST_TAGS[@]}"; do
            MANIFEST="${DOCKERHUB_REPOSITORY}:${MANIFEST_TAG}"
            IMAGES=()
            for ARCH in "${ARCHES[@]}"; do
              IMAGE="${DOCKERHUB_REPOSITORY}:${ARCH}-${MANIFEST_TAG}"
              if docker manifest inspect "${IMAGE}" 1>/dev/null 2>&1; then
                IMAGES+=("${IMAGE}")
              fi
            done
            docker manifest create "${MANIFEST}" "${IMAGES[@]}"
            docker manifest create "ghcr.io/${MANIFEST}" "${IMAGES[@]}"
            docker manifest push "${MANIFEST}"
            docker manifest push "ghcr.io/${MANIFEST}"
          done
  update_readme:
    name: README
    runs-on: ubuntu-latest
    needs: build_manifests
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.push)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
