---
name: build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DOCKERHUB_REPOSITORY: ksmanis/gentoo-distcc
  DOCKERHUB_USERNAME: ksmanis

jobs:
  images:
    strategy:
      fail-fast: false
      matrix:
        arch: ["386", "amd64", "arm/v6", "arm/v7", "arm64", "ppc64le"]
        target: ["tcp", "ssh"]
    name: ${{ matrix.arch }}:${{ matrix.target }} image
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      json: ${{ steps.docker-metadata.outputs.json }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Prepare build variables
        id: prep
        run: |
          {
            echo "qemu_platform=$(echo "${{ matrix.arch }}" | cut -d '/' -f 1)"
            echo "tag=$(echo "${{ matrix.arch }}" | tr -d '/')-${{ matrix.target }}"
          } >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: matrix.arch != '386' && matrix.arch != 'amd64'
        with:
          platforms: ${{ steps.prep.outputs.qemu_platform }}
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: Define Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.DOCKERHUB_REPOSITORY }}
            ghcr.io/${{ env.DOCKERHUB_REPOSITORY }}
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.title=gentoo-distcc
            org.opencontainers.image.authors=Konstantinos Smanis <konstantinos.smanis@gmail.com>
          tags: |
            type=ref,event=branch,prefix=${{ steps.prep.outputs.tag }}-,suffix=-{{sha}}
            type=ref,event=branch,prefix=${{ steps.prep.outputs.tag }}-
            type=ref,event=pr,prefix=${{ steps.prep.outputs.tag }}-pr-,suffix=-{{sha}}
            type=ref,event=pr,prefix=${{ steps.prep.outputs.tag }}-pr-
            type=raw,value=${{ steps.prep.outputs.tag }}-{{tag}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=${{ steps.prep.outputs.tag }},enable=${{ startsWith(github.ref, 'refs/tags/') }}
      - name: Build image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          labels: ${{ steps.docker-metadata.outputs.labels }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          platforms: linux/${{ matrix.arch }}
          target: distcc-${{ matrix.target }}
          load: true
      - name: Inspect image
        run: |
          docker image inspect ${{ steps.build.outputs.imageid }}
      - name: Build test image
        id: build-test
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          target: distcc-${{ matrix.target }}-test
          load: true
      - name: Test distcc
        env:
          IMAGE: ${{ steps.build.outputs.imageid }}
          TEST_IMAGE: ${{ steps.build-test.outputs.imageid }}
        run: |
          if [ '${{ matrix.target }}' = 'ssh' ]; then
            AUTHORIZED_KEYS="$(docker run --rm "${TEST_IMAGE}" cat .ssh/id_ed25519.pub)"
            export AUTHORIZED_KEYS
          fi
          docker-compose -f docker-compose.test.yml up \
            --abort-on-container-exit \
            --exit-code-from distcc-${{ matrix.target }}-client \
            distcc-${{ matrix.target }}-client distcc-${{ matrix.target }}-server
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          docker push --all-tags "docker.io/${DOCKERHUB_REPOSITORY}"
          docker push --all-tags "ghcr.io/${DOCKERHUB_REPOSITORY}"
  manifests:
    needs: images
    strategy:
      fail-fast: false
      matrix:
        target: ["tcp", "ssh"]
        tag: ${{ fromJson(needs.images.outputs.json).tags }}
    name: ${{ matrix.target }}:${{ matrix.tag }} manifest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Prepare build variables
        id: prep
        run: |
          tag_suffix="$(echo "${{ matrix.tag }}" | rev | cut -d ':' -f 1 | rev | cut -d '-' -f 3-)"
          {
            echo "registry=$(echo "${{ matrix.tag }}" | cut -d '/' -f 1)"
            echo "repo=$(echo "${{ matrix.tag }}" | cut -d ':' -f 1)"
            echo "tag=${{ matrix.target }}${tag_suffix:+-$tag_suffix}"
          } >> "$GITHUB_OUTPUT"
      - name: Log in to Docker Hub
        if: steps.prep.outputs.registry == 'docker.io'
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to GitHub Container registry
        if: steps.prep.outputs.registry == 'ghcr.io'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push manifest list
        env:
          REPO: ${{ steps.prep.outputs.repo }}
          TAG: ${{ steps.prep.outputs.tag }}
        run: |
          ./build-manifest.sh
  autotag:
    if: github.ref == 'refs/heads/master'
    needs: manifests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ssh-key: ${{ secrets.TAG_KEY }}
      - name: Tag new versions
        uses: salsify/action-detect-and-tag-new-version@v2.0.3
        with:
          version-command: |
            sed -n 's#^FROM ksmanis/stage3:\(\S\+\).*#\1#p' Dockerfile
          tag-template: "{VERSION}"
          tag-annotation-template: "Version {VERSION}"
