---
name: dockerhub-description

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/dockerhub-description.yml
      - README.md

env:
  DOCKERHUB_REPOSITORY: ksmanis/gentoo-distcc
  DOCKERHUB_USERNAME: ksmanis

jobs:
  dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          repository: ${{ env.DOCKERHUB_REPOSITORY }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
