name: lint

on: [push, pull_request]

jobs:
  shellcheck:
    name: Lint with shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run shellcheck
        run: bash -c 'shopt -s globstar nullglob; shellcheck **/*.sh'
